import Head from "next/head";
import Hero from "@/common/modules/Hero";
import GradientBackgroundImage from "@/common/components/backgrounds/GradientBackgroundImage";
import HeroGradientBackground from "@/assets/images/Hero.Gradient.svg";
import LargeRedGradientBackground from "@/assets/images/LargeRedBackground.Gradient.svg";
import FeatureGrid from "@/common/modules/FeatureGrid";
import FeatureContent from "@/common/modules/FeatureContent";
import UserReviews from "@/common/modules/UserReviews";
import StatNumbers from "@/common/modules/StatNumbers";
import FAQ from "@/common/modules/FAQ";
import CallToActionBlock from "@/common/modules/CallToActionBlock";
import Section from "@/common/components/containers/Section";
import FoundersNote from "@/common/modules/FoundersNote";
import LogoClouds from "@/common/modules/LogoClouds";
import GradientBackground from "@/common/components/backgrounds/GradientBackground";
import HeroContent from "@/content/Hero.Content";
import LogoCloudsContent from "@/content/LogoClouds.Content";
import FeatureGridContent from "@/content/FeatureGrid.Content";
import FirstFeatureContent from "@/content/FirstFeature.Content";
import SecondFeatureContent from "@/content/SecondFeature.Content";
import ThirdFeatureContent from "@/content/ThirdFeature.Content";
import UserReviewsContent from "@/content/UserReviews.Content";
import StatNumbersContent from "@/content/StatNumbers.Content";
import FAQContent from "@/content/FAQ.Content";
import CallToActionBlockContent from "@/content/CallToActionBlock.Content";
import FoundersNoteContent from "@/content/FoundersNote.Content";
import AppLayout from "@/common/layouts/AppLayout";

export default function LandingPage() {
  return (
    <>
      {/* Meta Tags */}
      <Head>
        <title>NextSiders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Hero Background Gradient Image */}
      <GradientBackgroundImage
        src={HeroGradientBackground}
        className="opacity-80"
      />

      <AppLayout>
        {/* Hero Section with Logo Clouds */}
        <Section>
          <Hero {...HeroContent} />
          <LogoClouds {...LogoCloudsContent} />
        </Section>

        {/* Feature Grid Section */}
        <Section background="lighter" id="features">
          <FeatureGrid {...FeatureGridContent} />
          <GradientBackground position="bottom-left" />
          <GradientBackground position="bottom-right" />
        </Section>

        {/* First Detailted Feature with Description */}
        <Section>
          <FeatureContent {...FirstFeatureContent} />
        </Section>

        {/* Second Detailted Feature with Description */}
        <Section background="lighter">
          <FeatureContent {...SecondFeatureContent} />
        </Section>

        {/* Third Detailted Feature with Description */}
        <Section>
          <FeatureContent {...ThirdFeatureContent} />
        </Section>

        {/* Testimonials Section */}
        <Section background="lighter" id="testimonials">
          <UserReviews {...UserReviewsContent} />
          <StatNumbers {...StatNumbersContent} />
        </Section>

        {/* FAQ Section */}
        <Section id="faq">
          <FAQ {...FAQContent} />
        </Section>

        {/* Call to Action Block Section */}
        <Section background="lighter">
          <CallToActionBlock {...CallToActionBlockContent} />
        </Section>

        {/* Founders Note Section */}
        <Section id="about">
          <GradientBackground position="top-left" />
          <GradientBackground position="top-right" />
          <GradientBackgroundImage
            src={LargeRedGradientBackground}
            position="bottom-0"
          />
          <FoundersNote {...FoundersNoteContent} />
        </Section>
      </AppLayout>
    </>
  );
}
